'use strict';
const app=(()=>{
const DATA_MANIFEST_URL='data/manifest-data.json';
const idx={year:0,week:1,date:2,ceco:3,store:4,ingredient:5,unit:6,provider:7,quantity:8,unitCost:9,totalCost:10,region:11,dm:12};
const monthNames=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const auditStates=['Conciliada','Falta Entrada','Falta Salida','Diferencia de Cantidad','Diferencia de Costo','Ingredientes Incompletos','Transferencia Parcial','Revisar','Coffee Patrol'];
const state={manifest:null,loadedChunks:new Map(),year:'',month:'',week:'',region:'',dm:'',store:'',ingredient:'',provider:'',status:'',direction:'',search:'',hideCoffee:true,view:'inicio',selectedTransfer:'',transfers:[],summary:[],allRows:[],dirByCeco:new Map(),storeByCeco:new Map()};
const el=id=>document.getElementById(id);
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2});
const qtyFmt=new Intl.NumberFormat('es-MX',{maximumFractionDigits:2});
const intFmt=new Intl.NumberFormat('es-MX',{maximumFractionDigits:0});
const peso=n=>money.format(Number(n)||0); const qty=n=>qtyFmt.format(Number(n)||0); const count=n=>intFmt.format(Number(n)||0);
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function debounce(fn,delay){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),delay);};}
function setMessage(msg){el('friendlyStatus').textContent=msg;} function setCount(msg){el('filterCount').textContent=msg;}
function normalize(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[_-]/g,' ').replace(/\s+/g,' ').trim();}
const decode={store:r=>state.manifest.dicts.tienda[r[idx.store]]||'',ingredient:r=>state.manifest.dicts.ingrediente[r[idx.ingredient]]||'',unit:r=>state.manifest.dicts.unidad[r[idx.unit]]||'',provider:r=>state.manifest.dicts.proveedor[r[idx.provider]]||'',region:r=>state.manifest.dicts.region[r[idx.region]]||'',dm:r=>state.manifest.dicts.dm[r[idx.dm]]||''};
function parseProviderCeco(provider){const m=String(provider||'').match(/^(\d{4,6})\b/);return m?m[1]:'';}
function cleanProviderName(provider){return String(provider||'').replace(/^\d{4,6}\s*SBUX\s*/i,'').replace(/_/g,' ').replace(/\s+/g,' ').trim();}
function directory(ceco){return state.dirByCeco.get(String(ceco))||{};}
function storeNameByCeco(ceco,fallbackProvider=''){const c=String(ceco||'');return state.storeByCeco.get(c)||directory(c).tienda||cleanProviderName(fallbackProvider)||fallbackProvider||'';}
function shortDate(iso){const d=new Date(`${iso}T00:00:00`); if(Number.isNaN(d.getTime()))return iso; return `${String(d.getDate()).padStart(2,'0')} ${monthNames[d.getMonth()].slice(0,3)}`;}
function isCoffeeProvider(provider){return /^38100\b/i.test(String(provider||''))||/coffee[_\s-]*patrol/i.test(String(provider||''));}
function closeAbs(a,b,tol=0.02){return Math.abs(Math.abs(Number(a)||0)-Math.abs(Number(b)||0))<=tol;}
function closeUnit(a,b,tol=0.02){return Math.abs((Number(a)||0)-(Number(b)||0))<=tol;}
function dateDistance(a,b){const da=new Date(`${a}T00:00:00`), db=new Date(`${b}T00:00:00`); if(Number.isNaN(da)||Number.isNaN(db))return 99; return Math.abs(da-db)/86400000;}
function statusClass(s){return normalize(s).replace(/\s+/g,'-');}
function isGoodStatus(s){return s==='Conciliada'||s==='Coffee Patrol';}
function fillSelect(select,values,selected,allLabel='Todos'){const current=selected||'';select.innerHTML=`<option value="">${allLabel}</option>`+values.map(v=>`<option value="${escapeHtml(v.value)}">${escapeHtml(v.label)}</option>`).join('');select.value=values.some(v=>String(v.value)===String(current))?current:'';}
async function init(){setMessage('Preparando información...');state.manifest=await fetch(DATA_MANIFEST_URL,{cache:'no-store'}).then(r=>r.json());for(const d of state.manifest.directory||[])state.dirByCeco.set(String(d.ceco),d);for(const [c,s] of Object.entries(state.manifest.cecoStores||{}))state.storeByCeco.set(String(c),s);bindNav();bindFilters();populateStaticFilters();await apply();registerServiceWorker();}
function populateStaticFilters(){const years=[...new Set((state.manifest.chunks||[]).map(c=>c.year))].sort((a,b)=>a-b).map(y=>({value:y,label:String(y)}));fillSelect(el('yearFilter'),years,state.year,'Todos');const monthValues=(state.manifest.months||[]).slice().sort((a,b)=>a.value-b.value).map(m=>({value:m.value,label:monthNames[m.value-1]}));fillSelect(el('monthFilter'),monthValues,state.month,'Todos');const weeks=(state.manifest.weeks||[]).slice().sort((a,b)=>Number(a)-Number(b)).map(w=>({value:w,label:String(w)}));fillSelect(el('weekFilter'),weeks,state.week,'Todas');const regions=[...new Set((state.manifest.directory||[]).map(d=>d.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).map(v=>({value:v,label:v}));fillSelect(el('regionFilter'),regions,state.region,'Todas');fillSelect(el('statusFilter'),auditStates.map(s=>({value:s,label:s})),state.status,'Todos');}
function bindFilters(){const bind=(id,key,fn)=>el(id).addEventListener('change',async e=>{state[key]=e.target.type==='checkbox'?e.target.checked:e.target.value;if(fn)fn();await apply();});bind('yearFilter','year');bind('monthFilter','month');bind('weekFilter','week');bind('regionFilter','region',()=>{state.dm='';state.store='';});bind('dmFilter','dm',()=>{state.store='';});bind('storeFilter','store');bind('ingredientFilter','ingredient');bind('providerFilter','provider');bind('statusFilter','status');bind('directionFilter','direction');bind('coffeeFilter','hideCoffee');el('searchFilter').addEventListener('input',debounce(async e=>{state.search=e.target.value.trim();await apply();},250));el('resetFilters').addEventListener('click',async()=>{Object.assign(state,{year:'',month:'',week:'',region:'',dm:'',store:'',ingredient:'',provider:'',status:'',direction:'',search:'',hideCoffee:true,selectedTransfer:''});document.querySelectorAll('select').forEach(s=>s.value='');el('searchFilter').value='';el('coffeeFilter').checked=true;populateStaticFilters();await apply();});}
function chunksForCurrentFilters(){let chunks=(state.manifest.chunks||[]).slice();if(state.year)chunks=chunks.filter(c=>String(c.year)===String(state.year));if(state.month)chunks=chunks.filter(c=>String(c.month)===String(state.month));if(state.week)chunks=chunks.filter(c=>(c.weeks||[]).map(String).includes(String(state.week)));return chunks;}
async function loadChunks(chunks){for(const chunk of chunks){if(!state.loadedChunks.has(chunk.id)){setMessage('Cargando transferencias filtradas...');const data=await fetch(chunk.path,{cache:'no-store'}).then(r=>r.json());state.loadedChunks.set(chunk.id,data.rows||[]);}}}
function currentRows(chunks){return chunks.flatMap(c=>state.loadedChunks.get(c.id)||[]);}
function rowMatchesTime(r){return (!state.year||String(r[idx.year])===String(state.year))&&(!state.month||String(new Date(`${r[idx.date]}T00:00:00`).getMonth()+1)===String(state.month))&&(!state.week||String(r[idx.week])===String(state.week));}
function updateDependentFilters(rows){const timeRows=rows.filter(rowMatchesTime);const regionDms=new Set(timeRows.filter(r=>!state.region||decode.region(r)===state.region).map(decode.dm).filter(Boolean));const dms=[...regionDms].sort((a,b)=>a.localeCompare(b,'es')).map(v=>({value:v,label:v}));if(state.dm&&!dms.some(d=>d.value===state.dm))state.dm='';fillSelect(el('dmFilter'),dms,state.dm,'Todos');const storeRows=timeRows.filter(r=>(!state.region||decode.region(r)===state.region)&&(!state.dm||decode.dm(r)===state.dm));const stores=[...new Set(storeRows.map(decode.store).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).map(v=>({value:v,label:v}));if(state.store&&!stores.some(s=>s.value===state.store))state.store='';fillSelect(el('storeFilter'),stores,state.store,'Todas');const visibleRows=storeRows.filter(r=>!state.store||decode.store(r)===state.store);const ingredients=[...new Set(visibleRows.map(decode.ingredient).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).slice(0,1800).map(v=>({value:v,label:v}));const providers=[...new Set(visibleRows.map(decode.provider).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).slice(0,1800).map(v=>({value:v,label:v}));if(state.ingredient&&!ingredients.some(x=>x.value===state.ingredient))state.ingredient='';if(state.provider&&!providers.some(x=>x.value===state.provider))state.provider='';fillSelect(el('ingredientFilter'),ingredients,state.ingredient,'Todos');fillSelect(el('providerFilter'),providers,state.provider,'Todos');}
function makeInputIndex(rows){const map=new Map();const all=[];for(const r of rows){if(!rowMatchesTime(r))continue;if(Number(r[idx.quantity])<=0||Number(r[idx.totalCost])<=0)continue;const providerCeco=parseProviderCeco(decode.provider(r));const key=[String(r[idx.ceco]),providerCeco,r[idx.ingredient],r[idx.unit]].join('|');const item={row:r,used:false};if(!map.has(key))map.set(key,[]);map.get(key).push(item);all.push(item);}for(const list of map.values())list.sort((a,b)=>a.row[idx.date].localeCompare(b.row[idx.date]));return{map,all};}
function productStatus(salida,ingreso){if(!ingreso)return'Falta Entrada';if(!closeAbs(salida[idx.quantity],ingreso[idx.quantity],0.001))return'Diferencia de Cantidad';if(!closeUnit(salida[idx.unitCost],ingreso[idx.unitCost],0.02)||!closeAbs(salida[idx.totalCost],ingreso[idx.totalCost],0.02))return'Diferencia de Costo';return'Conciliada';}
function compareSalida(salida,inputIndex){const provider=decode.provider(salida);if(isCoffeeProvider(provider))return{status:'Coffee Patrol',ingreso:null,diff:0,alert:'Excepción informativa. No exige entrada.'};const destCeco=parseProviderCeco(provider);if(!destCeco)return{status:'Revisar',ingreso:null,diff:Math.abs(Number(salida[idx.totalCost])||0),alert:'Proveedor no identificado.'};const key=[destCeco,String(salida[idx.ceco]),salida[idx.ingredient],salida[idx.unit]].join('|');const candidates=(inputIndex.map.get(key)||[]).filter(c=>!c.used);if(!candidates.length)return{status:'Falta Entrada',ingreso:null,diff:Math.abs(Number(salida[idx.totalCost])||0),alert:'Esta salida aún no tiene entrada relacionada.'};let best=null,score=9999;for(const c of candidates){const r=c.row;let s=0;if(!closeAbs(salida[idx.quantity],r[idx.quantity],0.001))s+=100;if(!closeUnit(salida[idx.unitCost],r[idx.unitCost],0.02))s+=30;if(!closeAbs(salida[idx.totalCost],r[idx.totalCost],0.02))s+=60;s+=Math.min(dateDistance(salida[idx.date],r[idx.date]),30);if(s<score){score=s;best=c;}}if(!best)return{status:'Falta Entrada',ingreso:null,diff:Math.abs(Number(salida[idx.totalCost])||0),alert:'Esta salida aún no tiene entrada relacionada.'};best.used=true;const st=productStatus(salida,best.row);return{status:st,ingreso:best.row,diff:Math.abs(Math.abs(Number(salida[idx.totalCost])||0)-Math.abs(Number(best.row[idx.totalCost])||0)),alert:st==='Conciliada'?'Transferencia conciliada.':'Revisar diferencia.'};}
function transferStatus(products,kind){if(kind==='coffee')return'Coffee Patrol';if(kind==='missingSalida')return'Falta Salida';const statuses=products.map(p=>p.status);if(statuses.every(s=>s==='Conciliada'))return'Conciliada';if(statuses.includes('Diferencia de Cantidad'))return'Diferencia de Cantidad';if(statuses.includes('Diferencia de Costo'))return'Diferencia de Costo';if(statuses.includes('Revisar'))return'Revisar';const matched=statuses.filter(s=>s==='Conciliada').length;const missing=statuses.filter(s=>s==='Falta Entrada').length;if(matched>0&&missing>0)return'Transferencia Parcial';if(missing===statuses.length)return'Falta Entrada';if(new Set(statuses).size>1)return'Ingredientes Incompletos';return'Revisar';}
function statusRank(s){return{'Falta Entrada':0,'Falta Salida':1,'Diferencia de Cantidad':2,'Diferencia de Costo':3,'Transferencia Parcial':4,'Ingredientes Incompletos':5,'Revisar':6,'Coffee Patrol':7,'Conciliada':8}[s]??9;}
function buildAllTransfers(rows){const inputIndex=makeInputIndex(rows);const groups=new Map();const salidaRows=rows.filter(r=>rowMatchesTime(r)&&Number(r[idx.quantity])<0&&Number(r[idx.totalCost])<0);for(const s of salidaRows){const provider=decode.provider(s);const coffee=isCoffeeProvider(provider);const destCeco=parseProviderCeco(provider);const destStore=storeNameByCeco(destCeco,provider);const destDir=directory(destCeco);const res=compareSalida(s,inputIndex);const key=[s[idx.year],s[idx.week],s[idx.date],s[idx.ceco],destCeco||provider].join('|');if(!groups.has(key))groups.set(key,{id:key,kind:coffee?'coffee':'salida',year:s[idx.year],week:s[idx.week],date:s[idx.date],originCeco:String(s[idx.ceco]),originStore:decode.store(s),originRegion:decode.region(s),originDm:decode.dm(s),destinationCeco:destCeco,destinationStore:destStore, destinationRegion:destDir.region||'', destinationDm:destDir.dm||'', provider, products:[]});groups.get(key).products.push({salida:s,ingreso:res.ingreso,status:res.status,diff:res.diff,alert:res.alert});}
for(const item of inputIndex.all){if(item.used)continue;const r=item.row;const provider=decode.provider(r);const originCeco=parseProviderCeco(provider);if(!originCeco)continue;const originStore=storeNameByCeco(originCeco,provider);const originDir=directory(originCeco);const key=[r[idx.year],r[idx.week],r[idx.date],originCeco,String(r[idx.ceco])].join('|');if(!groups.has(key))groups.set(key,{id:key,kind:'missingSalida',year:r[idx.year],week:r[idx.week],date:r[idx.date],originCeco,originStore,originRegion:originDir.region||'',originDm:originDir.dm||'',destinationCeco:String(r[idx.ceco]),destinationStore:decode.store(r),destinationRegion:decode.region(r),destinationDm:decode.dm(r),provider,products:[]});groups.get(key).products.push({salida:null,ingreso:r,status:'Falta Salida',diff:Math.abs(Number(r[idx.totalCost])||0),alert:'Esta entrada no tiene salida relacionada.'});}
return [...groups.values()].map(t=>finalizeTransfer(t));}
function finalizeTransfer(t){t.productCount=t.products.length;t.montoSalida=t.products.reduce((sum,p)=>sum+(p.salida?Math.abs(Number(p.salida[idx.totalCost])||0):0),0);t.montoIngreso=t.products.reduce((sum,p)=>sum+(p.ingreso?Math.abs(Number(p.ingreso[idx.totalCost])||0):0),0);t.diff=Math.abs(t.montoSalida-t.montoIngreso);t.status=transferStatus(t.products,t.kind);return t;}
function transferText(t){return normalize([t.originCeco,t.originStore,t.destinationCeco,t.destinationStore,t.provider,t.originRegion,t.originDm,t.destinationRegion,t.destinationDm,...t.products.flatMap(p=>[p.salida?decode.ingredient(p.salida):'',p.ingreso?decode.ingredient(p.ingreso):''])].join(' '));}
function transferHasIngredient(t){return !state.ingredient||t.products.some(p=>(p.salida&&decode.ingredient(p.salida)===state.ingredient)||(p.ingreso&&decode.ingredient(p.ingreso)===state.ingredient));}
function transferMatchesOrg(t){if(state.region&&t.originRegion!==state.region&&t.destinationRegion!==state.region)return false;if(state.dm&&t.originDm!==state.dm&&t.destinationDm!==state.dm)return false;if(state.store&&t.originStore!==state.store&&t.destinationStore!==state.store)return false;if(state.direction==='salidas'){if(state.store&&t.originStore!==state.store)return false;if(!state.store&&t.montoSalida<=0)return false;}if(state.direction==='entradas'){if(state.store&&t.destinationStore!==state.store)return false;if(!state.store&&t.montoIngreso<=0)return false;}return true;}
function applyTransferFilters(transfers){return transfers.filter(t=>{if(state.hideCoffee&&t.status==='Coffee Patrol')return false;if(state.status&&t.status!==state.status)return false;if(state.provider&&t.provider!==state.provider)return false;if(!transferHasIngredient(t))return false;if(!transferMatchesOrg(t))return false;if(state.search&&!transferText(t).includes(normalize(state.search)))return false;return true;}).sort((a,b)=>statusRank(a.status)-statusRank(b.status)||b.diff-a.diff||b.date.localeCompare(a.date)||a.originStore.localeCompare(b.originStore,'es'));}
function buildSummary(transfers){const byStore=new Map();function ensure(ceco,store,region,dm){const key=String(ceco)+'|'+store;if(!byStore.has(key))byStore.set(key,{ceco:String(ceco||''),store:store||'',region:region||'',dm:dm||'',transfers:0,conciliadas:0,pendientes:0,montoTransferido:0,montoConciliado:0,diff:0,statuses:new Map()});return byStore.get(key);}for(const t of transfers){const related=state.store?[state.store]:[t.originStore,t.destinationStore].filter(Boolean);const done=new Set();for(const store of related){const isOrigin=store===t.originStore, isDest=store===t.destinationStore;if(!isOrigin&&!isDest)continue;const ceco=isOrigin?t.originCeco:t.destinationCeco, region=isOrigin?t.originRegion:t.destinationRegion, dm=isOrigin?t.originDm:t.destinationDm;const key=ceco+'|'+store;if(done.has(key))continue;done.add(key);const item=ensure(ceco,store,region,dm);item.transfers++;if(isGoodStatus(t.status))item.conciliadas++;else item.pendientes++;item.montoTransferido+=t.montoSalida;item.montoConciliado+=t.montoIngreso;item.diff+=t.diff;item.statuses.set(t.status,(item.statuses.get(t.status)||0)+1);}}
return [...byStore.values()].map(item=>{item.status=overallStatus(item);return item;}).sort((a,b)=>statusRank(a.status)-statusRank(b.status)||b.diff-a.diff||a.store.localeCompare(b.store,'es'));}
function overallStatus(item){if(item.statuses.has('Falta Entrada'))return'Falta Entrada';if(item.statuses.has('Falta Salida'))return'Falta Salida';if(item.statuses.has('Diferencia de Cantidad'))return'Diferencia de Cantidad';if(item.statuses.has('Diferencia de Costo'))return'Diferencia de Costo';if(item.statuses.has('Transferencia Parcial'))return'Transferencia Parcial';if(item.statuses.has('Ingredientes Incompletos'))return'Ingredientes Incompletos';if(item.statuses.has('Revisar'))return'Revisar';if(item.statuses.has('Coffee Patrol')&&item.statuses.size===1)return'Coffee Patrol';return'Conciliada';}
async function apply(){try{setMessage('Preparando información...');const chunks=chunksForCurrentFilters();await loadChunks(chunks);const rows=currentRows(chunks);state.allRows=rows;updateDependentFilters(rows);const allTransfers=buildAllTransfers(rows);state.transfers=applyTransferFilters(allTransfers);state.summary=buildSummary(state.transfers);if(state.selectedTransfer&&!state.transfers.some(t=>t.id===state.selectedTransfer))state.selectedTransfer='';renderAll();setMessage(state.transfers.some(t=>!isGoodStatus(t.status))?'Hay salidas que requieren atención':'Revisión lista');}catch(err){console.error(err);setMessage('No fue posible completar la revisión.');}}
function renderAll(){const transfers=state.transfers;const metrics=computeMetrics(transfers);el('kpiGrid').innerHTML=[['Transferencias Totales',count(metrics.total),'movimientos auditados'],['Conciliadas',count(metrics.conciliadas),'sin diferencias'],['Pendientes',count(metrics.pendientes),'requieren atención'],['Parciales',count(metrics.parciales),'con productos pendientes'],['Sin Entrada',count(metrics.sinEntrada),'salida sin recepción'],['Sin Salida',count(metrics.sinSalida),'entrada sin salida'],['Diferencia de Cantidad',count(metrics.diffCantidad),'revisar piezas'],['Diferencia de Costo',count(metrics.diffCosto),'revisar importe'],['Monto Transferido',peso(metrics.montoTransferido),'salidas'],['Monto Conciliado',peso(metrics.montoConciliado),'entradas relacionadas'],['Diferencia Total',peso(metrics.diferencia),'oportunidad total']].map(([t,v,s])=>`<article class="kpi"><p>${t}</p><strong>${v}</strong><span>${s}</span></article>`).join('');setCount(transfers.length?'Revisión lista':'Selecciona filtros para iniciar');renderSummary('summaryRows',state.summary);renderSummary('auditRows',state.summary);el('summaryBadge').textContent=`${count(state.summary.length)} tiendas`;el('auditBadge').textContent=`${count(state.summary.length)} tiendas`;renderTransferCards();renderDetails();renderAlerts();}
function computeMetrics(transfers){return{total:transfers.length,conciliadas:transfers.filter(t=>t.status==='Conciliada').length,pendientes:transfers.filter(t=>!isGoodStatus(t.status)).length,parciales:transfers.filter(t=>t.status==='Transferencia Parcial'||t.status==='Ingredientes Incompletos').length,sinEntrada:transfers.filter(t=>t.status==='Falta Entrada').length,sinSalida:transfers.filter(t=>t.status==='Falta Salida').length,diffCantidad:transfers.filter(t=>t.status==='Diferencia de Cantidad').length,diffCosto:transfers.filter(t=>t.status==='Diferencia de Costo').length,montoTransferido:transfers.reduce((s,t)=>s+t.montoSalida,0),montoConciliado:transfers.reduce((s,t)=>s+t.montoIngreso,0),diferencia:transfers.reduce((s,t)=>s+t.diff,0)};}
function renderSummary(id,summary){el(id).innerHTML=summary.map(item=>`<tr class="clickable" data-store="${escapeHtml(item.store)}"><td><strong>${escapeHtml(item.store)}</strong></td><td>${escapeHtml(item.ceco)}</td><td>${escapeHtml(item.region)}</td><td>${escapeHtml(item.dm)}</td><td class="number">${count(item.transfers)}</td><td class="number positive">${count(item.conciliadas)}</td><td class="number negative">${count(item.pendientes)}</td><td class="number negative">${peso(item.montoTransferido)}</td><td class="number positive">${peso(item.montoConciliado)}</td><td class="number">${peso(item.diff)}</td><td><span class="status ${statusClass(item.status)}">${escapeHtml(item.status)}</span></td></tr>`).join('')||'<tr><td colspan="11">Selecciona filtros para iniciar la revisión.</td></tr>';el(id).querySelectorAll('tr[data-store]').forEach(tr=>tr.addEventListener('click',()=>{state.store=tr.dataset.store;el('storeFilter').value=state.store;state.selectedTransfer='';switchView('transferencias');apply();}));}
function renderTransferCards(){const selected=state.selectedTransfer;el('transferBadge').textContent=`${count(state.transfers.length)} transferencias`;el('transferCards').innerHTML=state.transfers.slice(0,420).map(t=>`<button class="transfer-card ${selected===t.id?'is-selected':''}" data-id="${escapeHtml(t.id)}" type="button"><span class="transfer-date">${escapeHtml(shortDate(t.date))}</span><strong>${escapeHtml(t.originStore)}</strong><span class="transfer-arrow">↓</span><span>${escapeHtml(t.destinationStore)}</span><div class="transfer-meta"><span>${count(t.productCount)} productos</span><span>${peso(t.montoSalida||t.montoIngreso)}</span></div><span class="status ${statusClass(t.status)}">${escapeHtml(t.status)}</span></button>`).join('')||'<p class="empty-state">No hay transferencias con los filtros actuales.</p>';el('transferCards').querySelectorAll('button[data-id]').forEach(btn=>btn.addEventListener('click',()=>{state.selectedTransfer=btn.dataset.id;renderTransferCards();renderDetails();}));}
function renderDetails(){const t=state.transfers.find(x=>x.id===state.selectedTransfer)||state.transfers[0];if(!t){el('detailTitle').textContent='Selecciona una transferencia';el('detailBadge').textContent='';el('detailRows').innerHTML='<tr><td colspan="9">No hay productos para mostrar.</td></tr>';return;}if(!state.selectedTransfer)state.selectedTransfer=t.id;el('detailTitle').textContent=`${shortDate(t.date)} · ${t.originStore} → ${t.destinationStore}`;el('detailBadge').textContent=`${count(t.productCount)} productos`;el('detailRows').innerHTML=t.products.map(p=>{const s=p.salida,i=p.ingreso,base=s||i;const unitCost=s?s[idx.unitCost]:(i?i[idx.unitCost]:0);return`<tr><td><strong>${escapeHtml(decode.ingredient(base))}</strong></td><td>${escapeHtml(decode.unit(base))}</td><td class="number negative">${s?qty(s[idx.quantity]):'—'}</td><td class="number positive">${i?qty(i[idx.quantity]):'—'}</td><td class="number">${peso(unitCost)}</td><td class="number negative">${s?peso(s[idx.totalCost]):'—'}</td><td class="number positive">${i?peso(i[idx.totalCost]):'—'}</td><td class="number">${peso(p.diff)}</td><td><span class="status ${statusClass(p.status)}">${escapeHtml(p.status)}</span></td></tr>`;}).join('');}
function renderAlerts(){const alerts=state.transfers.filter(t=>!isGoodStatus(t.status)).slice(0,200);el('alertBadge').textContent=`${count(alerts.length)} oportunidades`;el('alertList').innerHTML=alerts.map(t=>`<div class="alert-item"><strong>${escapeHtml(t.status)}</strong><span>${escapeHtml(shortDate(t.date))} · ${escapeHtml(t.originStore)} → ${escapeHtml(t.destinationStore)}</span><small>${count(t.productCount)} productos · ${peso(t.diff)} de diferencia</small></div>`).join('')||'<p class="empty-state">Transferencias revisadas sin diferencias relevantes.</p>';}
function bindNav(){document.querySelectorAll('.nav-card').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.section)));}
function switchView(view){state.view=view;document.querySelectorAll('.nav-card').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.section===view));document.querySelectorAll('.content-section').forEach(sec=>sec.classList.toggle('is-visible',sec.dataset.view===view));if(view==='transferencias'){renderTransferCards();renderDetails();}}
function registerServiceWorker(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(console.warn);}
document.addEventListener('DOMContentLoaded',init);
return{state,apply};
})();
