'use strict';
const app=(()=>{
const DATA_MANIFEST_URL='data/manifest-data.json';
const idx={year:0,week:1,date:2,ceco:3,store:4,ingredient:5,unit:6,provider:7,quantity:8,unitCost:9,totalCost:10,region:11,dm:12};
const monthNames=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const auditStates=['Conciliada','Ingreso con fecha diferente','Sin ingreso','Falta salida','Diferencia de cantidad','Diferencia de costo','Parcial','Coffee Patrol','Revisar'];
const COST_TOLERANCE=10;
const state={manifest:null,loadedChunks:new Map(),allRows:[],year:'',month:'',week:'',region:'',dm:'',store:'',ingredient:'',provider:'',status:'',direction:'',search:'',hideCoffee:true,view:'inicio',selectedTransfer:'',transfers:[],summary:[],dirByCeco:new Map(),storeByCeco:new Map()};
const el=id=>document.getElementById(id);
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2});
const qtyFmt=new Intl.NumberFormat('es-MX',{maximumFractionDigits:2});
const intFmt=new Intl.NumberFormat('es-MX',{maximumFractionDigits:0});
const peso=n=>money.format(Number(n)||0); const qty=n=>qtyFmt.format(Number(n)||0); const count=n=>intFmt.format(Number(n)||0);
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function normalize(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[_-]/g,' ').replace(/\s+/g,' ').trim();}
function debounce(fn,delay){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),delay);};}
function setMessage(msg){const n=el('friendlyStatus'); if(n)n.textContent=msg;} function setCount(msg){const n=el('filterCount'); if(n)n.textContent=msg;}
const decode={store:r=>state.manifest.dicts.tienda[r[idx.store]]||'',ingredient:r=>state.manifest.dicts.ingrediente[r[idx.ingredient]]||'',unit:r=>state.manifest.dicts.unidad[r[idx.unit]]||'',provider:r=>state.manifest.dicts.proveedor[r[idx.provider]]||'',region:r=>state.manifest.dicts.region[r[idx.region]]||'',dm:r=>state.manifest.dicts.dm[r[idx.dm]]||''};
function parseProviderCeco(provider){const m=String(provider||'').match(/^(\d{4,6})\b/);return m?m[1]:'';}
function cleanProviderName(provider){return String(provider||'').replace(/^\d{4,6}\s*SBUX\s*/i,'').replace(/_/g,' ').replace(/\s+/g,' ').trim();}
function directory(ceco){return state.dirByCeco.get(String(ceco))||{};}
function storeNameByCeco(ceco,fallback=''){const c=String(ceco||'');return state.storeByCeco.get(c)||directory(c).tienda||cleanProviderName(fallback)||fallback||'';}
function shortDate(iso){const d=new Date(`${iso}T00:00:00`); if(Number.isNaN(d.getTime()))return iso; return `${String(d.getDate()).padStart(2,'0')} ${monthNames[d.getMonth()].slice(0,3)}`;}
function isCoffeeProvider(provider){return /^38100\b/i.test(String(provider||''))||/coffee[_\s-]*patrol/i.test(String(provider||''));}
function abs(n){return Math.abs(Number(n)||0);} function diffAbs(a,b){return Math.abs(abs(a)-abs(b));}
function sameQty(a,b,tol=0.001){return diffAbs(a,b)<=tol;} function sameUnit(a,b,tol=0.02){return Math.abs((Number(a)||0)-(Number(b)||0))<=tol;}
function dateSerial(iso){const d=new Date(`${iso}T00:00:00`);return Number.isNaN(d.getTime())?0:d.getTime();}
function statusClass(s){return normalize(s).replace(/\s+/g,'-');}
function isGoodStatus(s){return s==='Conciliada'||s==='Ingreso con fecha diferente'||s==='Coffee Patrol';}
function statusRank(s){return {'Sin ingreso':1,'Falta salida':2,'Diferencia de cantidad':3,'Diferencia de costo':4,'Parcial':5,'Revisar':6,'Ingreso con fecha diferente':7,'Conciliada':8,'Coffee Patrol':9}[s]||10;}
function fillSelect(select,values,selected,allLabel='Todos'){const current=selected||'';select.innerHTML=`<option value="">${allLabel}</option>`+values.map(v=>`<option value="${escapeHtml(v.value)}">${escapeHtml(v.label)}</option>`).join('');select.value=values.some(v=>String(v.value)===String(current))?current:'';}
async function init(){setMessage('Preparando información...');state.manifest=await fetch(DATA_MANIFEST_URL,{cache:'no-store'}).then(r=>r.json());const updated=el('lastUpdated');if(updated&&state.manifest.latestUpdate){const [,m,d]=state.manifest.latestUpdate.split('-');updated.textContent=`Actualizado: ${d}/${m}`;}for(const d of state.manifest.directory||[])state.dirByCeco.set(String(d.ceco),d);for(const [c,s] of Object.entries(state.manifest.cecoStores||{}))state.storeByCeco.set(String(c),s);bindNav();bindFilters();populateStaticFilters();await apply();registerServiceWorker();}
function populateStaticFilters(){const years=[...new Set((state.manifest.chunks||[]).map(c=>c.year))].sort((a,b)=>a-b).map(y=>({value:y,label:String(y)}));fillSelect(el('yearFilter'),years,state.year,'Todos');const months=(state.manifest.months||[]).slice().sort((a,b)=>a.value-b.value).map(m=>({value:m.value,label:monthNames[m.value-1]}));fillSelect(el('monthFilter'),months,state.month,'Todos');const weeks=(state.manifest.weeks||[]).slice().sort((a,b)=>Number(a)-Number(b)).map(w=>({value:w,label:String(w)}));fillSelect(el('weekFilter'),weeks,state.week,'Todas');const regions=[...new Set((state.manifest.directory||[]).map(d=>d.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).map(v=>({value:v,label:v}));fillSelect(el('regionFilter'),regions,state.region,'Todas');fillSelect(el('statusFilter'),auditStates.map(s=>({value:s,label:s})),state.status,'Todos');}
function bindFilters(){const bind=(id,key,fn)=>el(id).addEventListener('change',async e=>{state[key]=e.target.type==='checkbox'?e.target.checked:e.target.value;if(fn)fn();await apply();});bind('yearFilter','year');bind('monthFilter','month');bind('weekFilter','week');bind('regionFilter','region',()=>{state.dm='';state.store='';});bind('dmFilter','dm',()=>{state.store='';});bind('storeFilter','store');bind('ingredientFilter','ingredient');bind('providerFilter','provider');bind('statusFilter','status');bind('directionFilter','direction');bind('coffeeFilter','hideCoffee');el('searchFilter').addEventListener('input',debounce(async e=>{state.search=e.target.value.trim();await apply();},250));el('resetFilters').addEventListener('click',async()=>{Object.assign(state,{year:'',month:'',week:'',region:'',dm:'',store:'',ingredient:'',provider:'',status:'',direction:'',search:'',hideCoffee:true,selectedTransfer:''});document.querySelectorAll('select').forEach(s=>s.value='');el('searchFilter').value='';el('coffeeFilter').checked=true;populateStaticFilters();await apply();});const pdf=el('exportPdf');if(pdf)pdf.addEventListener('click',exportPerformancePdf);}
async function loadAllChunks(){for(const chunk of state.manifest.chunks||[]){if(!state.loadedChunks.has(chunk.id)){setMessage('Cargando transferencias filtradas...');const data=await fetch(chunk.path,{cache:'no-store'}).then(r=>r.json());state.loadedChunks.set(chunk.id,data.rows||[]);}}state.allRows=[...state.loadedChunks.values()].flat();}
function rowMatchesTime(r){return (!state.year||String(r[idx.year])===String(state.year))&&(!state.month||String(new Date(`${r[idx.date]}T00:00:00`).getMonth()+1)===String(state.month))&&(!state.week||String(r[idx.week])===String(state.week));}
function updateDependentFilters(rows){const timeRows=rows.filter(rowMatchesTime);const regionRows=timeRows.filter(r=>!state.region||decode.region(r)===state.region);const dms=[...new Set(regionRows.map(decode.dm).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).map(v=>({value:v,label:v}));if(state.dm&&!dms.some(d=>d.value===state.dm))state.dm='';fillSelect(el('dmFilter'),dms,state.dm,'Todos');const dmRows=regionRows.filter(r=>!state.dm||decode.dm(r)===state.dm);const stores=[...new Set(dmRows.map(decode.store).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).map(v=>({value:v,label:v}));if(state.store&&!stores.some(s=>s.value===state.store))state.store='';fillSelect(el('storeFilter'),stores,state.store,'Todas');const visibleRows=dmRows.filter(r=>!state.store||decode.store(r)===state.store);const ingredients=[...new Set(visibleRows.map(decode.ingredient).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).slice(0,2000).map(v=>({value:v,label:v}));const providers=[...new Set(visibleRows.map(decode.provider).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).slice(0,2000).map(v=>({value:v,label:v}));if(state.ingredient&&!ingredients.some(x=>x.value===state.ingredient))state.ingredient='';if(state.provider&&!providers.some(x=>x.value===state.provider))state.provider='';fillSelect(el('ingredientFilter'),ingredients,state.ingredient,'Todos');fillSelect(el('providerFilter'),providers,state.provider,'Todos');}
function makeInputIndex(rows){const map=new Map();for(const r of rows){if(Number(r[idx.quantity])<=0||Number(r[idx.totalCost])<=0)continue;const originCeco=parseProviderCeco(decode.provider(r));const key=[String(r[idx.ceco]),originCeco,r[idx.ingredient],r[idx.unit]].join('|');const item={row:r,used:false};if(!map.has(key))map.set(key,[]);map.get(key).push(item);}for(const list of map.values())list.sort((a,b)=>dateSerial(a.row[idx.date])-dateSerial(b.row[idx.date]));return map;}
function bestInputForSalida(salida,inputIndex){const destCeco=parseProviderCeco(decode.provider(salida));if(!destCeco)return null;const key=[destCeco,String(salida[idx.ceco]),salida[idx.ingredient],salida[idx.unit]].join('|');const salidaTime=dateSerial(salida[idx.date]);const list=(inputIndex.get(key)||[]).filter(x=>!x.used&&dateSerial(x.row[idx.date])>=salidaTime);if(!list.length)return null;const exact=list.filter(x=>sameQty(salida[idx.quantity],x.row[idx.quantity])&&sameUnit(salida[idx.unitCost],x.row[idx.unitCost])&&diffAbs(salida[idx.totalCost],x.row[idx.totalCost])<=COST_TOLERANCE);const pool=exact.length?exact:list;pool.sort((a,b)=>dateSerial(a.row[idx.date])-dateSerial(b.row[idx.date]));return pool[0]||null;}
function lineStatus(salida,ingreso){if(!ingreso)return'Sin ingreso';if(!sameQty(salida[idx.quantity],ingreso[idx.quantity]))return'Diferencia de cantidad';if(!sameUnit(salida[idx.unitCost],ingreso[idx.unitCost])||diffAbs(salida[idx.totalCost],ingreso[idx.totalCost])>COST_TOLERANCE)return'Diferencia de costo';if(salida[idx.date]!==ingreso[idx.date])return'Ingreso con fecha diferente';return'Conciliada';}
function transferStatus(products,totalSalida,totalIngreso,isCoffee){if(isCoffee)return'Coffee Patrol';if(!products.some(p=>p.ingreso))return'Sin ingreso';if(products.some(p=>p.status==='Diferencia de cantidad'))return'Diferencia de cantidad';if(products.some(p=>p.status==='Diferencia de costo'))return'Diferencia de costo';if(products.some(p=>!p.ingreso))return'Parcial';if(Math.abs(totalSalida-totalIngreso)>COST_TOLERANCE)return'Diferencia de costo';if(products.some(p=>p.status==='Ingreso con fecha diferente'))return'Ingreso con fecha diferente';return'Conciliada';}
function buildSalidaTransfers(rows){const inputIndex=makeInputIndex(rows);const salidaRows=rows.filter(r=>Number(r[idx.quantity])<0&&Number(r[idx.totalCost])<0&&rowMatchesTime(r));const groups=new Map();for(const r of salidaRows){const key=[r[idx.year],r[idx.week],r[idx.date],String(r[idx.ceco]),decode.store(r),decode.provider(r)].join('|');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}const transfers=[];for(const [key,items] of groups){const first=items[0];const provider=decode.provider(first);const destCeco=parseProviderCeco(provider);const isCoffee=isCoffeeProvider(provider);const products=[];let entradaMin='';for(const s of items){let match=null;if(!isCoffee){const candidate=bestInputForSalida(s,inputIndex);if(candidate){candidate.used=true;match=candidate.row;entradaMin=!entradaMin||match[idx.date]<entradaMin?match[idx.date]:entradaMin;}}const st=lineStatus(s,match);products.push({salida:s,ingreso:match,status:isCoffee?'Coffee Patrol':st,diff:match?diffAbs(s[idx.totalCost],match[idx.totalCost]):abs(s[idx.totalCost])});}
const montoSalida=products.reduce((sum,p)=>sum+abs(p.salida?.[idx.totalCost]),0);const montoIngreso=products.reduce((sum,p)=>sum+abs(p.ingreso?.[idx.totalCost]),0);const diff=Math.abs(montoSalida-montoIngreso);const status=transferStatus(products,montoSalida,montoIngreso,isCoffee);const originCeco=String(first[idx.ceco]);const destName=storeNameByCeco(destCeco,provider);const destDir=directory(destCeco);const originDir=directory(originCeco);const id='S|'+key;transfers.push({id,type:'salida',date:first[idx.date],week:first[idx.week],year:first[idx.year],originCeco,originStore:decode.store(first),originRegion:decode.region(first)||originDir.region||'',originDm:decode.dm(first)||originDir.dm||'',destinationCeco:destCeco,destinationStore:destName,destinationRegion:destDir.region||'',destinationDm:destDir.dm||'',provider,entryDate:entradaMin,productCount:products.length,montoSalida,montoIngreso,diff,status,products});}
return {transfers,inputIndex};}
function buildMissingInputTransfers(rows,inputIndex){const missing=[];for(const list of inputIndex.values()){for(const item of list){if(item.used)continue;const r=item.row;if(!rowMatchesTime(r))continue;const provider=decode.provider(r);const originCeco=parseProviderCeco(provider);const originName=storeNameByCeco(originCeco,provider);const destCeco=String(r[idx.ceco]);const originDir=directory(originCeco);const destDir=directory(destCeco);const id=['E',r[idx.year],r[idx.week],r[idx.date],destCeco,provider,r[idx.ingredient],r[idx.unit]].join('|');missing.push({id,type:'entrada',date:r[idx.date],week:r[idx.week],year:r[idx.year],originCeco,originStore:originName,originRegion:originDir.region||'',originDm:originDir.dm||'',destinationCeco:destCeco,destinationStore:decode.store(r),destinationRegion:decode.region(r)||destDir.region||'',destinationDm:decode.dm(r)||destDir.dm||'',provider,entryDate:r[idx.date],productCount:1,montoSalida:0,montoIngreso:abs(r[idx.totalCost]),diff:abs(r[idx.totalCost]),status:'Falta salida',products:[{salida:null,ingreso:r,status:'Falta salida',diff:abs(r[idx.totalCost])}]});}}
return missing;}
function buildAllTransfers(rows){const salida=buildSalidaTransfers(rows);return salida.transfers.concat(buildMissingInputTransfers(rows,salida.inputIndex));}
function transferHasIngredient(t){return !state.ingredient||t.products.some(p=>decode.ingredient(p.salida||p.ingreso)===state.ingredient);}function transferText(t){return normalize([t.originCeco,t.originStore,t.destinationCeco,t.destinationStore,t.provider,t.status,t.products.map(p=>decode.ingredient(p.salida||p.ingreso)).join(' ')].join(' '));}
function orgMatches(t){if(state.region&&t.originRegion!==state.region&&t.destinationRegion!==state.region)return false;if(state.dm&&t.originDm!==state.dm&&t.destinationDm!==state.dm)return false;if(state.store&&t.originStore!==state.store&&t.destinationStore!==state.store)return false;if(state.direction==='salidas'&&state.store&&t.originStore!==state.store)return false;if(state.direction==='entradas'&&state.store&&t.destinationStore!==state.store)return false;if(state.direction==='salidas'&&!state.store&&t.montoSalida<=0)return false;if(state.direction==='entradas'&&!state.store&&t.montoIngreso<=0)return false;return true;}
function applyTransferFilters(transfers){return transfers.filter(t=>{if(state.hideCoffee&&t.status==='Coffee Patrol')return false;if(state.status&&t.status!==state.status)return false;if(state.provider&&t.provider!==state.provider)return false;if(!transferHasIngredient(t))return false;if(!orgMatches(t))return false;if(state.search&&!transferText(t).includes(normalize(state.search)))return false;return true;}).sort((a,b)=>statusRank(a.status)-statusRank(b.status)||b.diff-a.diff||b.date.localeCompare(a.date)||a.originStore.localeCompare(b.originStore,'es'));}
function buildSummary(transfers){const byStore=new Map();function ensure(ceco,store,region,dm){const key=String(ceco)+'|'+store;if(!byStore.has(key))byStore.set(key,{ceco:String(ceco||''),store:store||'',region:region||'',dm:dm||'',transfers:0,conciliadas:0,pendientes:0,desfase:0,montoTransferido:0,montoConciliado:0,diff:0,statuses:new Map()});return byStore.get(key);}for(const t of transfers){const related=state.store?[state.store]:[t.originStore,t.destinationStore].filter(Boolean);const done=new Set();for(const store of related){const isOrigin=store===t.originStore,isDest=store===t.destinationStore;if(!isOrigin&&!isDest)continue;const ceco=isOrigin?t.originCeco:t.destinationCeco,region=isOrigin?t.originRegion:t.destinationRegion,dm=isOrigin?t.originDm:t.destinationDm;const key=ceco+'|'+store;if(done.has(key))continue;done.add(key);const item=ensure(ceco,store,region,dm);item.transfers++;if(isGoodStatus(t.status))item.conciliadas++;else item.pendientes++;if(t.status==='Ingreso con fecha diferente')item.desfase++;item.montoTransferido+=t.montoSalida;item.montoConciliado+=t.montoIngreso;item.diff+=t.diff;item.statuses.set(t.status,(item.statuses.get(t.status)||0)+1);}}
return [...byStore.values()].map(item=>{item.status=overallStatus(item);return item;}).sort((a,b)=>statusRank(a.status)-statusRank(b.status)||b.diff-a.diff||a.store.localeCompare(b.store,'es'));}
function overallStatus(item){if(item.statuses.has('Sin ingreso'))return'Sin ingreso';if(item.statuses.has('Falta salida'))return'Falta salida';if(item.statuses.has('Diferencia de cantidad'))return'Diferencia de cantidad';if(item.statuses.has('Diferencia de costo'))return'Diferencia de costo';if(item.statuses.has('Parcial'))return'Parcial';if(item.statuses.has('Revisar'))return'Revisar';if(item.statuses.has('Ingreso con fecha diferente'))return'Ingreso con fecha diferente';if(item.statuses.has('Coffee Patrol')&&item.statuses.size===1)return'Coffee Patrol';return'Conciliada';}
async function apply(){try{setMessage('Preparando información...');await loadAllChunks();updateDependentFilters(state.allRows);const all=buildAllTransfers(state.allRows);state.transfers=applyTransferFilters(all);state.summary=buildSummary(state.transfers);if(state.selectedTransfer&&!state.transfers.some(t=>t.id===state.selectedTransfer))state.selectedTransfer='';renderAll();setMessage(state.transfers.some(t=>!isGoodStatus(t.status))?'Hay salidas que requieren atención':'Revisión lista');}catch(err){console.error(err);setMessage('No fue posible completar la revisión.');}}
function computeMetrics(transfers){const total=transfers.length, conciliadas=transfers.filter(t=>t.status==='Conciliada').length, desfase=transfers.filter(t=>t.status==='Ingreso con fecha diferente').length, pendientes=transfers.filter(t=>!isGoodStatus(t.status)).length;const montoTransferido=transfers.reduce((s,t)=>s+t.montoSalida,0),montoConciliado=transfers.reduce((s,t)=>s+t.montoIngreso,0),diferencia=transfers.reduce((s,t)=>s+t.diff,0);return{total,conciliadas,desfase,pendientes,parciales:transfers.filter(t=>t.status==='Parcial').length,sinIngreso:transfers.filter(t=>t.status==='Sin ingreso').length,faltaSalida:transfers.filter(t=>t.status==='Falta salida').length,diffCantidad:transfers.filter(t=>t.status==='Diferencia de cantidad').length,diffCosto:transfers.filter(t=>t.status==='Diferencia de costo').length,montoTransferido,montoConciliado,diferencia,pctConciliacion:total?((conciliadas+desfase)/total*100):0,pctIncidencias:total?(pendientes/total*100):0};}
function renderAll(){const transfers=state.transfers;const m=computeMetrics(transfers);el('kpiGrid').innerHTML=[['Transferencias',count(m.total),'revisadas'],['Conciliadas',count(m.conciliadas),'mismo día'],['Ingreso con fecha diferente',count(m.desfase),'entrada posterior'],['Sin ingreso',count(m.sinIngreso),'salida sin recepción'],['Diferencia de cantidad',count(m.diffCantidad),'revisar piezas'],['Diferencia de costo',count(m.diffCosto),'más de $10'],['Monto enviado',peso(m.montoTransferido),'salidas'],['Monto recibido',peso(m.montoConciliado),'entradas'],['Diferencia total',peso(m.diferencia),'oportunidad']].map(([t,v,s])=>`<article class="kpi"><p>${t}</p><strong>${v}</strong><span>${s}</span></article>`).join('');setCount(transfers.length?'Revisión lista':'Selecciona filtros para iniciar');renderSummary('summaryRows',state.summary);renderSummary('auditRows',state.summary);el('summaryBadge').textContent=`${count(state.summary.length)} tiendas`;el('auditBadge').textContent=`${count(state.summary.length)} tiendas`;renderTransferCards();renderDetails();renderAlerts();renderPerformance(m);}
function renderSummary(id,summary){el(id).innerHTML=summary.map(item=>`<tr class="clickable" data-store="${escapeHtml(item.store)}"><td><strong>${escapeHtml(item.store)}</strong></td><td>${escapeHtml(item.ceco)}</td><td>${escapeHtml(item.region)}</td><td>${escapeHtml(item.dm)}</td><td class="number">${count(item.transfers)}</td><td class="number positive">${count(item.conciliadas)}</td><td class="number warning">${count(item.desfase)}</td><td class="number negative">${count(item.pendientes)}</td><td class="number negative">${peso(item.montoTransferido)}</td><td class="number positive">${peso(item.montoConciliado)}</td><td class="number">${peso(item.diff)}</td><td><span class="status ${statusClass(item.status)}">${escapeHtml(item.status)}</span></td></tr>`).join('')||'<tr><td colspan="12">Selecciona filtros para iniciar la revisión.</td></tr>';el(id).querySelectorAll('tr[data-store]').forEach(tr=>tr.addEventListener('click',()=>{state.store=tr.dataset.store;el('storeFilter').value=state.store;state.selectedTransfer='';switchView('transferencias');apply();}));}
function renderTransferCards(){const selected=state.selectedTransfer;el('transferBadge').textContent=`${count(state.transfers.length)} transferencias`;el('transferCards').innerHTML=state.transfers.slice(0,500).map(t=>`<button class="transfer-card ${selected===t.id?'is-selected':''}" data-id="${escapeHtml(t.id)}" type="button"><span class="transfer-date">${escapeHtml(shortDate(t.date))}${t.entryDate&&t.entryDate!==t.date?` · Entrada ${escapeHtml(shortDate(t.entryDate))}`:''}</span><strong>${escapeHtml(t.originStore)}</strong><span class="transfer-arrow">↓</span><span>${escapeHtml(t.destinationStore)}</span><div class="transfer-meta"><span>${count(t.productCount)} productos</span><span>${peso(t.montoSalida||t.montoIngreso)}</span></div><span class="status ${statusClass(t.status)}">${escapeHtml(t.status)}</span></button>`).join('')||'<p class="empty-state">No hay transferencias con los filtros actuales.</p>';el('transferCards').querySelectorAll('button[data-id]').forEach(btn=>btn.addEventListener('click',()=>{state.selectedTransfer=btn.dataset.id;renderTransferCards();renderDetails();}));}
function renderDetails(){const t=state.transfers.find(x=>x.id===state.selectedTransfer)||state.transfers[0];if(!t){el('detailTitle').textContent='Selecciona una transferencia';el('detailBadge').textContent='';el('detailSubtotal').innerHTML='';el('detailRows').innerHTML='<tr><td colspan="10">No hay productos para mostrar.</td></tr>';return;}if(!state.selectedTransfer)state.selectedTransfer=t.id;el('detailTitle').textContent=`${shortDate(t.date)} · ${t.originStore} → ${t.destinationStore}`;el('detailBadge').textContent=`${count(t.productCount)} productos`;el('detailSubtotal').innerHTML=`<div><span>Fecha salida</span><strong>${escapeHtml(shortDate(t.date))}</strong></div><div><span>Fecha entrada</span><strong>${t.entryDate?escapeHtml(shortDate(t.entryDate)):'—'}</strong></div><div><span>Total salida</span><strong>${peso(t.montoSalida)}</strong></div><div><span>Total entrada</span><strong>${peso(t.montoIngreso)}</strong></div><div><span>Diferencia</span><strong>${peso(t.diff)}</strong></div>`;el('detailRows').innerHTML=t.products.map(p=>{const s=p.salida,i=p.ingreso,base=s||i;const unitCost=s?s[idx.unitCost]:(i?i[idx.unitCost]:0);return`<tr><td><strong>${escapeHtml(decode.ingredient(base))}</strong></td><td>${escapeHtml(decode.unit(base))}</td><td>${s?escapeHtml(shortDate(s[idx.date])):'—'}</td><td>${i?escapeHtml(shortDate(i[idx.date])):'—'}</td><td class="number negative">${s?qty(s[idx.quantity]):'—'}</td><td class="number positive">${i?qty(i[idx.quantity]):'—'}</td><td class="number">${peso(unitCost)}</td><td class="number negative">${s?peso(s[idx.totalCost]):'—'}</td><td class="number positive">${i?peso(i[idx.totalCost]):'—'}</td><td><span class="status ${statusClass(p.status)}">${escapeHtml(p.status)}</span></td></tr>`;}).join('');}
function renderAlerts(){const alerts=state.transfers.filter(t=>!isGoodStatus(t.status)).slice(0,250);el('alertBadge').textContent=`${count(alerts.length)} oportunidades`;el('alertList').innerHTML=alerts.map(t=>`<div class="alert-item"><strong>${escapeHtml(t.status)}</strong><span>${escapeHtml(shortDate(t.date))} · ${escapeHtml(t.originStore)} → ${escapeHtml(t.destinationStore)}</span><small>${count(t.productCount)} productos · ${peso(t.diff)} de diferencia</small></div>`).join('')||'<p class="empty-state">Transferencias revisadas sin diferencias relevantes.</p>';}
function topBy(list, keyFn, valueFn, limit=5){const m=new Map();for(const item of list){const k=keyFn(item);if(!k)continue;m.set(k,(m.get(k)||0)+valueFn(item));}return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit);}
function renderPerformance(m){const node=el('performanceBody');if(!node)return;const incidencias=state.transfers.filter(t=>!isGoodStatus(t.status));const byDest=topBy(incidencias,t=>t.destinationStore,t=>1);const byProduct=topBy(incidencias.flatMap(t=>t.products),p=>decode.ingredient(p.salida||p.ingreso),p=>1);node.innerHTML=`<div class="performance-grid"><article><p>% conciliación</p><strong>${m.pctConciliacion.toFixed(1)}%</strong><span>incluye ingresos con fecha diferente</span></article><article><p>% incidencias</p><strong>${m.pctIncidencias.toFixed(1)}%</strong><span>pendientes operativos</span></article><article><p>Fecha diferente</p><strong>${count(m.desfase)}</strong><span>requieren seguimiento ligero</span></article><article><p>Diferencia > $10</p><strong>${count(m.diffCosto)}</strong><span>requieren revisión de costo</span></article></div><div class="insight-grid"><div><h4>Destinos con incidencias</h4>${byDest.map(([k,v])=>`<p><strong>${escapeHtml(k)}</strong><span>${count(v)} casos</span></p>`).join('')||'<p>Sin incidencias.</p>'}</div><div><h4>Productos con incidencias</h4>${byProduct.map(([k,v])=>`<p><strong>${escapeHtml(k)}</strong><span>${count(v)} casos</span></p>`).join('')||'<p>Sin incidencias.</p>'}</div><div><h4>Alertas principales</h4><p><strong>Sin ingreso</strong><span>${count(m.sinIngreso)} casos</span></p><p><strong>Ingreso con fecha diferente</strong><span>${count(m.desfase)} casos</span></p><p><strong>Diferencia de costo</strong><span>${count(m.diffCosto)} casos</span></p></div></div>`;}
function currentFilterLabels(){return [['Año',state.year||'Todos'],['Mes',state.month?monthNames[Number(state.month)-1]:'Todos'],['Semana',state.week||'Todas'],['Región',state.region||'Todas'],['DM',state.dm||'Todos'],['Tienda',state.store||'Todas'],['Estado',state.status||'Todos']];}
function exportPerformancePdf(){const m=computeMetrics(state.transfers);const rows=state.summary.slice(0,80).map(s=>`<tr><td>${escapeHtml(s.store)}</td><td>${escapeHtml(s.region)}</td><td>${escapeHtml(s.dm)}</td><td>${count(s.transfers)}</td><td>${count(s.conciliadas)}</td><td>${count(s.pendientes)}</td><td>${peso(s.diff)}</td><td>${escapeHtml(s.status)}</td></tr>`).join('');const filters=currentFilterLabels().map(([k,v])=>`<span><b>${k}:</b> ${escapeHtml(v)}</span>`).join(' ');const html=`<!doctype html><html><head><meta charset="utf-8"><title>Desempeño Transferencias</title><style>body{font-family:Arial,sans-serif;color:#0f2a20;margin:28px}h1{color:#006241} .filters span{margin-right:14px;display:inline-block}.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0}.kpi{border:1px solid #cfe2da;border-radius:12px;padding:12px}.kpi p{margin:0;color:#557066;font-size:11px;text-transform:uppercase}.kpi strong{font-size:20px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border-bottom:1px solid #cfe2da;padding:7px;text-align:left}th{color:#006241;background:#eef8f3}@page{size:letter portrait;margin:1.2cm}</style></head><body><h1>Desempeño de Transferencias</h1><p>Generado: ${new Date().toLocaleString('es-MX')}</p><div class="filters">${filters}</div><div class="kpis"><div class="kpi"><p>Transferencias</p><strong>${count(m.total)}</strong></div><div class="kpi"><p>Conciliación</p><strong>${m.pctConciliacion.toFixed(1)}%</strong></div><div class="kpi"><p>Incidencias</p><strong>${m.pctIncidencias.toFixed(1)}%</strong></div><div class="kpi"><p>Monto enviado</p><strong>${peso(m.montoTransferido)}</strong></div><div class="kpi"><p>Monto recibido</p><strong>${peso(m.montoConciliado)}</strong></div><div class="kpi"><p>Diferencia</p><strong>${peso(m.diferencia)}</strong></div></div><h2>Resumen por tienda</h2><table><thead><tr><th>Tienda</th><th>Región</th><th>DM</th><th>Transferencias</th><th>Conciliadas</th><th>Pendientes</th><th>Diferencia</th><th>Estado</th></tr></thead><tbody>${rows}</tbody></table><script>window.print();</script></body></html>`;const w=window.open('','_blank','noopener,noreferrer');if(w){w.document.write(html);w.document.close();}}
function bindNav(){document.querySelectorAll('.nav-card').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.section)));}
function switchView(view){state.view=view;document.querySelectorAll('.nav-card').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.section===view));document.querySelectorAll('.content-section').forEach(sec=>sec.classList.toggle('is-visible',sec.dataset.view===view));if(view==='transferencias'){renderTransferCards();renderDetails();}}
function registerServiceWorker(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(console.warn);}
document.addEventListener('DOMContentLoaded',init);
return{state,apply};
})();
